- name: Créer une nouvelle VM Debian
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: false
    datacenter: "{{ vm_datacenter }}"
    cluster: "{{ vm_cluster }}"
    folder: "{{ vm_folder }}"
    name: "{{ vm_name }}"
    state: poweredon
    guest_id: "{{ vm_guest_id }}"
    disk:
      - size_gb: "{{ vm_disk_size_gb }}"
        type: thin
        datastore: "{{ vm_datastore }}"
    hardware:
      memory_mb: "{{ vm_memory_mb }}"
      num_cpus: "{{ vm_num_cpus }}"
    networks:
      - name: "{{ vm_network }}"
        type: static
    wait_for_ip_address: false
  delegate_to: localhost
