---
# handlers file for roles/install-package
- name: Editer /etc/vim/vimrc
  ansible.builtin.blockinfile:
    path: /etc/vim/vimrc
    marker: '" {mark} ANSIBLE MANAGED BLOCK'
    block: |
      set nu
      colorscheme torte
  become: true
