---
# tasks file for roles/install-package
- name: Mettre à jour le cache des paquets
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Installer les paquets nécessaires
  ansible.builtin.apt:
    name:
      - git
      - vim
      - openssh-server
      - curl
      - net-tools
      - dnsutils
      - sudo
      - unzip
      - nfs-client 
    state: present
  become: true

#---

- name: Vérifier si vim est installé
  package_facts:
    manager: "auto"
  
#- name: Notifier le handler si vim est installé
#  ansible.builtin.debug:
#    msg: "Vim est installé, on applique la config"
#  when: "'vim' in ansible_facts.packages"
#  notify: Editer /etc/vim/vimrc

- name: Forcer le déclenchement du handler si vim est installé
  ansible.builtin.set_fact:
    vim_trigger: true
  changed_when: true
  when: "'vim' in ansible_facts.packages"
  notify: Editer /etc/vim/vimrc
