---
# tasks file for roles/install-package
- name: Mettre à jour le cache des paquets avec dnf
  ansible.builtin.dnf:
    update_cache: true
  become: true

- name: Installer les paquets nécessaires
  ansible.builtin.dnf:
    name:
      - git
      - vim
      - openssh-server
      - curl
      - net-tools
      - dnsutils
      - sudo
      - unzip  
    state: present
  become: true 
